site:
  title: Ordnungen der HHU
  url: https://hhu-ordnungen.github.io/ordnungen/
  start_page: Satzung/Satzung.adoc
content:
  sources:
    - url: https://github.com/HHU-Ordnungen/Satzung.git
ui:
  bundle:
    url: https://gitlab.com/antora/antora-ui-default/-/jobs/artifacts/HEAD/raw/build/ui-bundle.zip?job=bundle-stable
    snapshot: true
